---

- name: Detect if rubies are installed
  command: '{{ rvm1_rvm }} {{ item }} do true'
  changed_when: False
  failed_when: False
  register: detect_rubies
  with_items: '{{ rvm1_rubies }}'
  when: rvm1_rubies is defined and rvm1_rubies | length > 0

- name: Install rubies
  command: '{{ rvm1_rvm }} install {{ item.item }} {{ rvm1_ruby_install_flags }}'
  when: rvm1_rubies is defined and rvm1_rubies | length > 0 and item.rc|default(0) != 0
  with_items: '{{ detect_rubies.results }}'

- name: Detect default ruby version
  command: '{{ rvm1_rvm }} alias list default'
  changed_when: False
  register: detect_default_ruby_version

- name: Select default ruby
  command: '{{ rvm1_rvm }} alias create default {{ rvm1_default_ruby_version }}'
  when: detect_default_ruby_version.stdout|default() == '' or
        rvm1_default_ruby_version not in detect_default_ruby_version.stdout

- name: Detect installed ruby patch number
  shell: >
    {{ rvm1_rvm }} list strings | grep {{ item }} | tail -n 1
  with_items: '{{ rvm1_rubies }}'
  changed_when: False
  register: ruby_patch
  check_mode: no # Run in normal mode when in --check mode (http://docs.ansible.com/ansible/playbooks_checkmode.html)

- name: Install bundler if not installed
  shell: >
    ls {{ rvm1_install_path }}/wrappers/{{ item.stdout }}
    | if ! grep "^bundler " ; then {{ rvm1_install_path }}/wrappers/{{ item.stdout }}/gem install bundler ; fi
  args:
    creates: '{{ rvm1_install_path }}/wrappers/{{ item.stdout }}/bundler'
  with_items: '{{ ruby_patch.results }}'
  when: rvm1_bundler_install
  register: bundler_install
  changed_when: '"Successfully installed bundler" in bundler_install.stdout'

- name: Symlink ruby related binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm1_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm1_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
  when: not '--user-install' in rvm1_install_flags
  with_items: '{{ rvm1_symlink_binaries }}'

- name: Symlink bundler binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm1_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm1_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
  when: not '--user-install' in rvm1_install_flags and rvm1_bundler_install
  with_items: '{{ rvm1_symlink_bundler_binaries }}'

- name: List installed ruby versions (for deletion)
  command: '{{ rvm1_rvm }} list strings'
  changed_when: False
  register: rvm1_list_installed_rubies
  when: rvm1_delete_unmanaged_rubies or (rvm1_delete_ruby is defined and rvm1_delete_ruby != '')
  check_mode: no # Run in normal mode when in --check mode (http://docs.ansible.com/ansible/playbooks_checkmode.html)

- name: Delete unmanaged ruby versions
  command: '{{ rvm1_rvm }} remove {{ item }}'
  register: rvm_delete_rubies_command_result
  when: rvm1_delete_unmanaged_rubies
  with_items: '{{ rvm1_list_installed_rubies.stdout_lines | difference(rvm1_rubies|default([])) }}'

- name: '[DEPRECATED] Delete {{ rvm1_delete_ruby }}'
  command: '{{ rvm1_rvm }} remove {{ rvm1_delete_ruby }}'
  register: rvm_delete_command_result
  changed_when: "'#removing' in rvm_delete_command_result.stdout"
  when:
    - not rvm1_delete_unmanaged_rubies|bool
    - rvm1_delete_ruby is defined and rvm1_delete_ruby != ''
    - rvm1_delete_ruby in rvm1_list_installed_rubies.stdout_lines
